### ISSUE TITLE
feature: request headers form

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#10]
## Task

This is part of requirements of GraphQL route:
```Header section that can be shown or hidden, user-added headers are sent to the server 20 points```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement feature, that allows user to add headers for the request.

At this moment you should implement only one input. Input object will be JSON string with headers.

This includes:

- [x] Add accordion (spoiler) with multiple items able to be expanded
- [x] Add headers form
- [x] Implement sending headers to server

### Add accordion (spoiler)

If not already exists (due to previous connected task), add accordion with multiple items able to be expanded.

### Add headers form

Put in accordion (spoiler) item, named Headers form with textarea. Headers form have to contain label, with reminder to use JSON.

### Implement sending headers to server

Input object have to be included in URL, in query parameters, with name "headers", minified and urlencoded.
This have happen if only headers object not empty.

On server side you have to handle headers query parameter, parse into object and pass them into gql-fetch.

If there any error in parsing headers, return error before gql-fetch.
