### ISSUE TITLE
feature: request variables form

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#11]
## Task

This is part of requirements of GraphQL route:
```Variables section that can shown or hidden, specified variables are sent to the server 30 points```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement feature, that allows user to add variables for the request.

At this moment you should implement only one input. Input object will be JSON string with variables .

This includes:

- [x] Add accordion (spoiler) with multiple items able to be expanded
- [x] Add variables form
- [x] Implement sending variables to server

### Add accordion (spoiler)

If not already exists (due to previous connected task), add accordion with multiple items able to be expanded.

### Add variables form

Put in accordion (spoiler) item, named Variables form with textarea. Variables form have to contain label, with reminder to use JSON.

### Implement sending variables to server

Input object have to be included in URL, in query parameters, with name "variables", minified and urlencoded.
This have happen if only variables object not empty.

On server side you have to handle variables query parameter, parse into object and pass them into gql-fetch.

If there any error in parsing variables, return error before gql-fetch.
