### ISSUE TITLE
feature: json response prettifying

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#12]
## Task

This is part of requirements of GraphQL route:
```Response section with an editor in read-only as a JSON viewer 40 points```

Take note that any libraries for prettifying is prohibited, this mentioned in penalties
"Usage 3rd party / open source libraries for prettifying"

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement feature, that allows user to browse the result of request in JSON, auto-prettified, in read only mode (at this moment textarea).

**Place utils functions in separate files in /src/lib/utils**

This includes:

- [x] Implement prettifying JSON function
- [x] Add automatic prettify once response received
- [x] Add request/response error displayed in UI

### Implement prettifying JSON function

Seems like solution [Link](https://stackoverflow.com/questions/4810841/pretty-print-json-using-javascript)

Takes as input string of response JSON, and return's object. On successful response prettifying, object contains only "response" type of sting with prettified query. On any errors detected, return object contains "error" type of string.

### Add automatic prettify once response received

Once response JSON received, it have to be prettified. Textarea with prettified response have to be read only.

### Add request/response error displayed in UI

If there any request/response error, place it in separate line below textarea.

In request could happen errors, as a response can contains API error object.
