### ISSUE TITLE
feature: welcome page

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#15]
## Task

This is part of requirements in "Welcome route":

### In scoring we have

```
The welcome page should contain general information about the developers, project, and course 10 points
In the upper right corner there are 2 buttons: Sign In and Sign Up 10 points
If the login token is valid and unexpired, the Sign In and Sign Up buttons are replaced with the "Main Page" button 10 points
```

### In task description we have

```
If the user is not authorized, the page should contain a link to Sign In / Sign Up page.
If the user is authorized, the page should contain a link to the Main page.
```

### In google-sheets we have

```
If user is authenticated, the link on the Welcome page will navigate him to the Main page (GraphiQL). Logout button should be on the header.
```

```
Q: 
  ""The header must include a link to the welcome page, language control switch, and a sign out button"
  1. Can we relocate all the necessary buttons to other areas in the app, such as placing the language switch in the settings or move the link to welcome page to the navigation bar?
  2. Also сan we choose the location of all possible buttons, menus and all the ui on the page ourselves?"

A:
  "I would suggest adhering to the given requirements to avoid confusions during the cross check (and avoid possible low points)"
```

```
Q:
  ""In the upper right corner there are 2 buttons: Sign In and Sign Up 10 points"
  Welcome page
  "If the user is not authorized, the page should contain a link to Sign In / Sign Up page."
  Is this means that we need to duplicate buttons Sign In and Sign Up from Header on the upper right corner on Welcome page and they will be located under the Header buttons?"

A: 
  "Yes, that's correct."
```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You supposed to implement "welcome page, in root directory of App Router ("src/app/page.tsx"). and
Current page in root directory have to be moved to level down, into "editor" directory."

But at this moment of time, just put it in "src/welcome/page.tsx"

This includes:

* [ ] Add Hero section
* [ ] Add App description section
* [ ] Add Our team section
* [ ] Add Course reference section

### Hero section
This block is separated on 2 vertical columns.
In first column, could be some clickbait image. May be editor interface, may be some connected image.
In second column, block is separated on 2 vertical columns: in first column short title, under it description which can catch eye of potential user, in second column buttons "2 buttons: Sign In and Sign Up", so we could follow requirements.

### App description section

Describe benefits of using this app, included functions.

### Add Course reference section

Describe project as part of course.
