### ISSUE TITLE
feature: header

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#18]
## Task

This is part of "General requirements" requirements:

```Sticky header 10 points```

### In task description we have

```
The header should be sticky. The moment it becomes sticky (if there is a scroll on a page) should be animated: color can be changed or its height can become smaller.
Animated sticky header
Link to Welcome page
Control that allows user to switch the language
You should be able to change the language by clicking on the toggler/select in the header.
Sign Out button - signs user out

```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement footer part of page's layout.

This includes:

* [ ] Add link to welcome page
* [ ] Add link language switch control
* [ ] Add SignOut and SingIn buttons
* [ ] Implement sticky behavior
