### ISSUE TITLE
feature: signup page

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#19]
# THIS IS DRAFT. AWAIT ANNOUNCEMENT

## Task

This is part of "Sign In / Sign Up" requirements:

```Client-side validation is implemented 20 points```

### In task description we have

```
Client-side validation should be implemented (email and password strength - minimum 8 symbols, at least one letter, one digit, one special character, Unicode passwords must be supported)
If the user is already logged in and tries to reach these routes, they should be redirected to the Main page
For the authentication you should use Firebase with the email/password sign-in method.
```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement SignUp page.

This page will allow user to sing up (register).

The main content of page should consist of one visual block encapsulationg all sign up features.

Also on page have to be link to sign in page, so user could easily switch to sign ip page and not stuck in flow.
This link is not main focus of page, but definitely have to be something that user see in third order during overlooking of page.

Sign up input field should have cliend side validation, so thire is no posibility to send request untill all fields is valid.

Errors of validation have to be displayed near it's filed (could be under the field or other place, depending on layout), but have to be uniformly of both fields.

Errors of register (unlike than validation errors) should be shown in different place, depending on layout.

You can use react hook form, but you have to use yup (to speed up develop process, but in case of complexity or any other trubbles could be changed).

This also inclueds some changes in API routes.

Please, firstly implement API logic features, helpers and other. In process cooperate with @nvalkovich so you can share same styles of compentes and may be some parts of client side validation.

This includes:

* [ ] Implement name field 
* [ ] Implement email field
* [ ] Implement password field
* [ ] Implement password repeat field
* [ ] Implement accept T&C checkbox
* [ ] Implement client-side validation
* [ ] Implement password strength indication
* [ ] Implement link to sign in page
* [ ] Implement redirected to the Main page
* [ ] Correct logic inside API route
* [ ] Handle erros and display them

### Name field 

Name of user, have be at least 2 symbols.

### Email field

Email of user, have to be valid email.

### Password field

User passord, have to be:

- at least 8 symbols
- at least one letter,
- at least one digit
- at least one special character
- **Unicode passwords must be supported**

Password field shuld indicated password strength.

### Password repeat field

Repeat of user password, have to be identical with password to be valid.

### Client-side validation

For speed up coding process use React Hook Form and Yup.

### Password strength indication

You have to add custom indicator of password strength.

Everything below requirements of valid password is weak password.
Everything above requirements should have at least 2 stages of strength.

###  Link to sign in page
Add link to sign up page in form of button or something else.

Could be followed by some description text

### Redirected to the Main page

"If the user is already logged in and tries to reach these routes, they should be redirected to the Main page".

Possibly this should be done in middleware instead of page.

### Correct logic inside API route
API route /api/auth/register/route.ts must handle new field (name)

API route /api/auth/register/route.ts have to be correted:

to response with erros and text of error
to handle exections
to return appropriate error codes

### Handle erros and display them

Handle erros from server and display them in user firendly form.
