### ISSUE TITLE
feature: signin page

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#20]
## Task

This is part of "Sign In / Sign Up" and "Welcome route" requirements:

```
Upon successful login, the user is redirected to the Main page 10 points
If the user is already logged in and tries to reach these routes, they should be redirected to the Main page 10 points
When the token expires - the user should be redirected to the "Welcome page" automatically 10 points
```

### In task description we have

```
For the authentication you should use Firebase with the email/password sign-in method. Please, check this article
Upon successful login, the user should be redirected to the Main page
If the user is already logged in and tries to reach these routes, they should be redirected to the Main page
```

### In google-sheets we have

```
Q: "Can we use Supabase instead of Firebase?"
A: "Yes"
```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement SignIn page.

Page should consist of two auth methods: pair or email/password and google. 

Also on page have to be link to sign up page, so user could easily switch to sign up page and not stuck in flow.
This link is not main focus of page, but definitely have to be something that user see in third order during overlooking of page.

Two methods of auth should be in one visual block (to highlight their same functionality - to auth user), but have to be separated from each other visually to underline their difference.

Password and email have to use client side validation, so thire is no posibility to send request untill this fields is valid.

Errors of validation have to be displayed near it's filed (could be under the field or other place, depending on layout), but have to be uniformly of both fields.

Errors of auth (unlike than validation errors) should be shown in different place, depending on layout.

You can use react hook form, but you should use yup (to speed up develop process, but in case of complexity or any other trubbles could be changed).

This includes:

* [x] Implement email field
* [x] Implement password field
* [x] Implement alternative method
* [x] Implement client side validation
* [x] Implement link to sign up
* [x] Implement redirected to the Main page
* [x] Correct logic inside API route
* [x] Handle erros  and display them

### Implement alternative method

User should have ability to sign in with google.

This is alternative method, so on page, it have to be in second order (goes after default method, depending on layout)

### Implement client side validation

On cliend side should be validation of fields email and password.

- email should be valid email address
- password should be at least 8 symbols

### Implement link to sign up

Add link to sign up page in form of button or something else. 

Could be followed by some description text

### Redirected to the Main page

"Upon successful login, the user should be redirected to the Main page"

and also:

"If the user is already logged in and tries to reach these routes, they should be redirected to the Main page".

Possibly this should be done in middleware instead of page.

### Correct logic inside API route

API route ```/api/auth/route.ts``` shuld be correted:

- to response with erros and text of error
- to handle exections
- to return appropriate error codes

### Handle erros  and display them

Handle erros from server and display them in user firendly form.
