### ISSUE TITLE
feature: url input

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#33]
## Task

This is part of "Main page" requirements:

```
Work with a user-specified open GraphQL endpoint.
```

### In task description we have

```
Change Endpoint button - allows the user to switch to an arbitrary GraphQL endpoint.
```

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement feature that allows user to change url to any url user specified

This includes:

* [ ] Implement input and save button
* [ ] Implement adding url to search params
* [ ] Implement reading url from search params
* [ ] Correct suspense key

### Implement input and save button

Add input with label and save button to change url

### Implement adding url to search params

After clicking on save button, url have to be updated in current URL.

### Implement reading url from search params

All components that use url, should be updated from hardcoded url to reading in from shearh prams

### Correct suspense key

Suspence key have to be corrected and include url, data, headers, variabels.
