### ISSUE TITLE
Research how to use Context API with NextJS App Router in scope of localization of our app

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#4]
### Our task requirements
We have requiremt:
"Localization (at least 2 languages). 
You should be able to change the language by clicking on the toggler/select in the header. 
Localization should be implemented using **Context API**.
_No 3rd party / open-source solutions are allowed._"

### Tasks:

- [x] Find out is it possible to use Context API with NextJS App Router
- [x] Find out how we can use Context API to create Localization
- [x] Find out what problems we can face
