### ISSUE TITLE
feature: header navigation menu

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#89]
## Task

This feature adds a navigation menu to the header. When there is not enough space to show usal navigation, the burger menu has to be shown. This aso adds small tablet and mobile adaptive versions of the header.

## Description

This includes:

- [ ] Add a navigation to the header blocks
- [ ] Add adaptive versions of header
- [ ] Add navigation menu and related buttons

### Add a navigation to the header
Update the content of the header, and place the navigation after the logo and before other 

The navigation has to contain:

- Main page link
- Editor page link

### Add adaptive versions of header

The adaptive version of the header with the navigation menu button has to contain:

- left side: Signn button
- middle: logo
- right side: button to open burger menu.

On different screen width sizes, the header has to have a different height.

_Some screen width sizes could share the same header height._

### Add navigation menu and related buttons

Add a navigation menu (burger menu) to the small tablet and mobile versions.

The navigation menu has to be opened after the navigation menu button is clicked.

The navigation menu has to contain:

- SingIn button (depending on current auth state)
- SignUp button (depending on current auth state)
- SignOut button (depending on current auth state)
- Language selector
- Main page link
- Editor page link
