### ISSUE TITLE
feature: graphql query prettifying

### ISSUE THREAD

**Issue by thirdmadman** [thirdmadman/graphiql-app#9]
## Task

This is part of requirements of GraphQL route:
```Functional editor enabling query editing and prettifying 60 points```

Take note that any libraries for prettifying is prohibited, this mentioned in penalties 
"Usage 3rd party / open source libraries for prettifying"

## Description

Follow this convention in naming for branches: [Link](https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4)

You should implement feature, that allows user to prettify (format) GraphQL query in editor (at this moment textarea).

**Place utils functions in separate files in /src/lib/utils**

This includes:

- [x] Implement prettifying function
- [x] Implement minifying function
- [x] Add prettifying button to UI
- [x] Add minifying in chain of onSubmit action handler
- [x] Add prettifying error displayed in UI

### Implement prettifying function

Takes as input string GraphQL query, and return's object. On successful query prettifying, object contains only "query" type of sting with prettified query. On any errors detected, return object contains "error" type of string.

We have algorithm suggested in answers sheet:

```
1. split the query into lines
2. Iterate through each line
        a. remove leading and trailing whitespaces
        b. ignore empty lines
        c. decrease the indentation level for closing braces
        d. add the indented line to the prettified query
        e. increase the indentation level for opening braces
```

### Minifying function

Result of func should look like string inside output field of this codepen [Link](https://codepen.io/dangodev/pen/Baoqmoy)

Takes as input string GraphQL query, and return's string. On successful query minifying returns result string. On any errors detected returns source string.

### Prettifying button

Place "Prettify" in the line with Execute button

### Prettifying error

If there any prettifying error, place it in separate line below Execute and Prettify buttons.
